### ISSUE TITLE
Aggregrator service discovery doesn't differentiate between stage and prod

### ISSUE THREAD

**Issue by limed** [nubisproject/prometheus-aggregator#2]
Service discovery doesn't have environment tags

**Comment by gozer** [comment]
For which services, specifically ?

**Comment by limed** [comment]
Specifically

`
host federator-prometheus.service.consul
`

**Comment by limed** [comment]
See https://github.com/gozer/nubis-puppet-prometheus/pull/3 where its being tracked and fixed
